version: "3"

services:

  jre:
    container_name: dmx-jre
    image: dimajix/jre:oracle-8
    build:
      context: .
      args:
        JAVA_PACKAGE: server-jre
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}

  jdk:
    container_name: dmx-jdk
    image: dimajix/jdk:oracle-8
    build:
      context: .
      args:
        JAVA_PACKAGE: jdk
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}

networks:
  default:
    external:
      name: dimajix

